swagger: '2.0'
info:
  description: This is a sample server for Assignment 2 of COMP9322. This will implement a Dentist information system.
  version: '1.0'
  title: Dentist Service
  contact:
    email: jatin.gupta@student.unsw.edu.au
host: api.example.com.au
basePath: /v1
schemes: 
- https
- http
paths:
  /dentists/{id}:
    get:
      operationId: get_dentist_details
      parameters:
      - name: id
        in: path
        description: ID of the dentist
        required: true
        type: integer
        format: int64
      - name: If-Modified-Since
        type: string
        in: header
        description: E-tag
      tags: 
      - Dentists
      summary: Returns the details of a dentist
      description: Get the details of a dentist from Dentist service
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      responses:
        200:
          description: OK
          headers:
            Cache-Control:
              description: Cache directive
              type: string
          schema:
              type: object
              properties:
                data:
                  $ref: '#/definitions/Doctor'
        304:
          description: Not Modified
        400:
          description: Bad Request, Invalid parameters
        404:
          description: Not Found


  /dentists:
    get:
      operationId: get_dentists
      parameters:
      - name: name
        type: string
        in: query
        description: Name of doctor
      - name: If-Modified-Since
        type: string
        in: header
        description: E-tag
      tags: 
      - Dentists
      summary: Returns the list of a dentist
      description: Get the list of dentists from Dentist service
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      responses:
        200:
          description: OK
          headers:
            Cache-Control:
              description: Cache directive
              type: string
          schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/definitions/Doctor'
        304:
          description: Not Modified
        400:
          description: Bad Request, Invalid parameters


definitions:
  Specialization:
    type: string
    enum: [Orthodontics, Paediatric Dentistry, Oral Surgery]

  Doctor:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 123
      name:
        type: string
        example: Dr. Jhon Doe
      location:
        type: string
        example: Mascot
      specialization:
        $ref: '#/definitions/Specialization'
      links:
        type: array
        items:
          type: object
          properties:
            get:
              $ref: '#/definitions/_self'
              
  _self:
    type: object
    properties:
      rel:
        type: string
        example: self
      href:
        type: string
        example: /dentists/{id}
